DROP TABLE IF EXISTS usuarios;

CREATE TABLE usuarios (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   nome TEXT NOT NULL
);

CREATE TABLE evento (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   nome TEXT NOT NULL
);